development:
  oauth_consumer_key: ""
  oauth_consumer_secret: ""
  site: "https://api.linkedin.com"
  request_token_path: "C:\linkedin\oauth\requestToken"
  authorize_path: "C:\linkedin\oauth\authorize"
  access_token_path: "C:\linkedin\oauth\accessToken"
  oauth_callback: "http://localhost:3000/authenticate/persist"